language: java
before_install:
  # download the latest android sdk and unzip
  - wget http://dl.google.com/android/android-sdk_r22.3-linux.tgz
  - tar -zxf android-sdk_r22.3-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  # Add 32-bit libraries as ADK needs them.
  - sudo apt-get update -qq
  - sudo apt-get install -qq libstdc++6:i386 libgcc1:i386 zlib1g:i386 libncurses5:i386
  # only update the sdk for the tools and platform-tools (1,2) and whatever api level
  # you are building for android (run "android list sdk" to get the full list.  9 = 2.3.3 or API level 10
  - echo "y"| android update sdk --filter 1,2 --no-ui --force
  - echo "y"| android update sdk --filter build-tools-19.0.1,android-19,addon-google_apis-google-19  --no-ui --force
